### PR TITLE
Setup background worker for contact mailer

### PR DESCRIPTION
**Pull request by breethomas**

### CODE REVIEW

**Comment by breethomas** [comment]
Don't merge this guy. We never setup config file for pushing this to production, so it would likely break some stuff!

**Comment by srt32** [comment]
Good to merge! @bwinterling @breethomas @Egogre

**Comment by srt32** [comment]
With this last commit running `foreman start` from your command line in dev will start the rails server and the worker

**Comment by srt32** [comment]
Any objections to my merging this guy in @breethomas @bwinterling @Egogre ?

**Comment by breethomas** [comment]
No objection from me....
:+1:

**Pull request merged**
